theme: jekyll-theme-minimal
title: Travis Jungroth
# description: [A short description of your site's purpose]
show_downloads: false
logo: https://github.com/travisjungroth/travisjungroth.github.io/blob/master/travis_jungroth_telescope.jpeg?raw=true
markdown: GFM
google_analytics: UA-156179069-1
